inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  Exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'spec/**/*'
  - 'db/schema.rb'
  - 'db/**/*'
  - 'config/**/*'
  - 'Guardfile'
  - 'bin/**/*'
  - 'lib/price-simulator/**/*'
  - 'tmp/**/*'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 65

Metrics/PerceivedComplexity:
  Max: 17

Metrics/ModuleLength:
  Max: 160
