version: 2.1

orbs:
  slack: circleci/slack@4.1

executors:
  rails_executor:
    docker:
      # https://hub.docker.com/r/cimg/ruby
      - image: cimg/ruby:<< parameters.ruby_version_tag >>
      # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/postgres/images
      - image: circleci/postgres:<< parameters.pg_version_tag >>
        environment:
          - POSTGRES_USER: root
          - POSTGRES_PASSWORD: postgres
          - POSTGRES_DB: suikoden_election_2021_test
    parameters:
      ruby_version_tag:
        type: string
        default: '3.0.2'
      pg_version_tag:
        type: string
        default: '13.2'

jobs:
  build:
    executor:
      name: rails_executor
      ruby_version_tag: '3.0.2'
      pg_version_tag: '13.2'
    environment:
      TZ: "Asia/Tokyo"
    working_directory: ~/working_directory
    steps:
      - checkout
      # TODO: Setup Database, bundle install, bundle exec rubocop, bundle exec rspec
      - restore_cache:
          name: Restore RubyGems Cache
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Prepare the artifact directory
          command: |
            mkdir /tmp/bluemoon
      - run:
          name: Hello, World!
          command: |
            echo 'Hello, World!'
      - run:
          name: Check Ruby version
          command: |
            ruby -v > /tmp/my_artifact
      - run:
          name: Check the installed Ruby path
          command: |
            which ruby > /tmp/bluemoon/which_ruby.txt
      - run:
          name: Install the latest Bundler
          command: |
            gem install bundler
      - run:
          name: Bundle install
          command: |
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          name: Save RubyGems Cache
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Execute RuboCop
          command: |
            bundle exec rubocop
      - run:
          name: Execute RSpec
          command: |
            mkdir -p /tmp/test_results /tmp/screenshots
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test_results/rspec.xml \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - slack/notify:
          channel: notice-circleci
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Suikoden Election 2021 (Database)",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
      - store_artifacts:
          path: /tmp/my_artifact
          destination: discord_log_storage
      - store_artifacts:
          path: /tmp/bluemoon
      - store_test_results:
          path: /tmp/test_results
      - store_artifacts:
          path: /tmp/screenshots
          destination: rspec_screenshot
