default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV['RAILS_MAX_THREADS'] || Rails.application.credentials[:rails_max_threads] || 5 %>

production:
  <<: *default
  database: suikoden_election_2021_production
  host: <%= ENV['POSTGRES_HOST_PRODUCTION'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_PRODUCTION'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_PRODUCTION'] || 'suikoden_election_2021' %>
  password: <%= ENV['POSTGRES_PASSWORD_PRODUCTION'] || 'suikoden_election_2021' %>

development:
  <<: *default
  database: suikoden_election_2021_development
  host: <%= ENV['POSTGRES_HOST_DEVELOPMENT'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_DEVELOPMENT'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_DEVELOPMENT'] || 'suikoden_election_2021' %>
  password: <%= ENV['POSTGRES_PASSWORD_DEVELOPMENT'] || 'suikoden_election_2021' %>

test:
  <<: *default
  database: suikoden_election_2021_test
  host: <%= ENV['POSTGRES_HOST_DEVELOPMENT'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_DEVELOPMENT'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_DEVELOPMENT'] || 'suikoden_election_2021' %>
  password: <%= ENV['POSTGRES_PASSWORD_DEVELOPMENT'] || 'suikoden_election_2021' %>

tweet_storage:
  <<: *default
  database: ENV['TWEET_STORAGE_DATABASE']
  host: ENV['TWEET_STORAGE_HOST']
  port: ENV['TWEET_STORAGE_PORT']
  username: ENV['TWEET_STORAGE_USERNAME']
  password: ENV['TWEET_STORAGE_PASSWORD']
